### ISSUE TITLE
Error during the installation

### ISSUE THREAD

**Issue by liorko87** [scipr-lab/libiop#11]
Hello,

I'm trying to install the library and encountered this error:
```
error: #error C++11 or greater detected. Should be C++03.
 #error C++11 or greater detected. Should be C++03.
```

OS Version: Ubuntu 18.04.3 LTS
GCC Version: 7.4.0

**EDIT** : When I removed these lines from the `CMakeLists.txt` , the problem solved:
```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

**Comment by ValarDragon** [comment]
Sorry for the issue with this! I'll remove these lines for now (they just got added)

@npwardberkeley 
Any idea why these made it work on your system and broke it on Ubuntu?
It works on my machine(s) without these lines as well:
Mac Os version: 10.14.6
clang version: Apple LLVM version 10.0.1 (clang-1001.0.46.4)

Ubuntu Version:
Ubuntu 18.04.2 LTS
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

**Comment by ValarDragon** [comment]
Closing this for now, since we've reverted and it works.

I think this was an issue with using inconsistent cmake versions. The fix that we put in (and removed) depended on Cmake 3.1 features, but the repo currently expects cmake 2.8.

I'm planning on upgrading the cmake to 3.15, which should hopefully prevent similar issues in the future.
